{{- if .Values.components.blockchainIngestion.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-money-tracking.fullname" . }}-blockchain-ingestion
  labels:
    {{- include "smart-money-tracking.labels" . | nindent 4 }}
    app.kubernetes.io/component: blockchain-ingestion
spec:
  replicas: {{ .Values.components.blockchainIngestion.replicas }}
  selector:
    matchLabels:
      {{- include "smart-money-tracking.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: blockchain-ingestion
  template:
    metadata:
      labels:
        {{- include "smart-money-tracking.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: blockchain-ingestion
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: blockchain-ingestion
          image: "{{ .Values.image.registry }}/{{ .Values.components.blockchainIngestion.image.repository }}:{{ .Values.components.blockchainIngestion.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- toYaml .Values.components.blockchainIngestion.env | nindent 12 }}
            - name: POSTGRES_HOST
              value: "{{ include "smart-money-tracking.fullname" . }}-postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.auth.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "smart-money-tracking.fullname" . }}-postgresql-secret
                  key: postgresql-password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ include "smart-money-tracking.fullname" . }}-kafka:9092"
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: data-volume
              mountPath: /app/data
            - name: logs-volume
              mountPath: /app/logs
          resources:
            {{- toYaml .Values.components.blockchainIngestion.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ include "smart-money-tracking.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "smart-money-tracking.fullname" . }}-data-pvc
        - name: logs-volume
          persistentVolumeClaim:
            claimName: {{ include "smart-money-tracking.fullname" . }}-logs-pvc
        {{- else }}
        - name: data-volume
          emptyDir: {}
        - name: logs-volume
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-money-tracking.fullname" . }}-blockchain-ingestion
  labels:
    {{- include "smart-money-tracking.labels" . | nindent 4 }}
    app.kubernetes.io/component: blockchain-ingestion
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smart-money-tracking.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: blockchain-ingestion
{{- end }}