apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-money-tracking.fullname" . }}-blockchain-secrets
  labels:
    {{- include "smart-money-tracking.labels" . | nindent 4 }}
type: Opaque
data:
  ethereum-rpc-url: {{ .Values.secrets.blockchain.ethereumRpcUrl | b64enc }}
  ethereum-websocket-url: {{ .Values.secrets.blockchain.ethereumRpcUrl | replace "https://" "wss://" | b64enc }}
  polygon-rpc-url: {{ .Values.secrets.blockchain.polygonRpcUrl | b64enc }}
  polygon-websocket-url: {{ .Values.secrets.blockchain.polygonRpcUrl | replace "https://" "wss://" | b64enc }}
  arbitrum-rpc-url: {{ .Values.secrets.blockchain.arbitrumRpcUrl | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-money-tracking.fullname" . }}-postgresql-secret
  labels:
    {{- include "smart-money-tracking.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc }}
  postgresql-postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-money-tracking.fullname" . }}-minio-secret
  labels:
    {{- include "smart-money-tracking.labels" . | nindent 4 }}
type: Opaque
data:
  root-user: {{ .Values.minio.auth.rootUser | b64enc }}
  root-password: {{ .Values.minio.auth.rootPassword | b64enc }}

---
{{- if .Values.secrets.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-money-tracking.fullname" . }}-monitoring-secrets
  labels:
    {{- include "smart-money-tracking.labels" . | nindent 4 }}
type: Opaque
data:
  slack-webhook-url: {{ .Values.secrets.slack.webhookUrl | b64enc }}
  {{- if .Values.secrets.email.smtpHost }}
  smtp-host: {{ .Values.secrets.email.smtpHost | b64enc }}
  smtp-port: {{ .Values.secrets.email.smtpPort | toString | b64enc }}
  smtp-username: {{ .Values.secrets.email.username | b64enc }}
  smtp-password: {{ .Values.secrets.email.password | b64enc }}
  {{- end }}
{{- end }}