apiVersion: v2
name: smart-money-tracking
description: A Helm chart for Smart Money Tracking MLOps pipeline
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - blockchain
  - smart-money
  - mlops
  - data-pipeline
home: https://github.com/videv93/Smart-Money-Tracking
sources:
  - https://github.com/videv93/Smart-Money-Tracking
maintainers:
  - name: vitr
    email: your-email@domain.com
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kafka
    version: 26.8.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: minio
    version: 12.10.0
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 7.0.19
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled